In [1]:
from sklearn.linear_model import Perceptron

x = [[0,0],[0,1],[1,0],[1,1]]
t = [0,1,1,1]

model = Perceptron()
model.fit(x,t)
model.score(x,t)
#   x1   x2   t
#    0   0    0
#    0   1    1
#    1   0    1
#    1   1    1


1.0

In [2]:
x1 = [[0.5,0.5],[-0.5,-0.5],[10,2.3],[-1,-2]]
y1 = model.predict(x1)
model.score(x1,y1)


1.0

In [3]:
x1 = [[0.5,0.5],[-0.5,-0.5],[10,2.3],[-1,-2]]
y1 = model.predict(x1)
model.score(x1,y1)
print(y1)

[1 0 1 0]


In [4]:
x1 = [[0.5,0.5],[0.5,0],[0,0.5],[0.4,0]]
y1 = model.predict(x1)
model.score(x1,y1)
print(y1)

[1 0 0 0]


In [5]:
from sklearn.linear_model import Perceptron

x = [[-0.5,-0.5],[-0.5,0.5],[0.5,-0.5],[-0.1,1]]
t = [1,1,0,0]
model = Perceptron()
model.fit(x,t)
model.score(x,t)


1.0

In [6]:
x1 = [[2,2],[-2,-2],[0.5,-0.5],[-0.1,1]]
y1 = model.predict(x1)
model.score(x1,y1)
print(y1)

[0 1 0 0]


In [7]:
from sklearn.linear_model import Perceptron
from sklearn import datasets 
from sklearn.model_selection import train_test_split
#du lieu da train ko dc dung de test

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler  #scale du lieu  de xu  li (du lieu ko deu, vd cot y gia tri tu 1 toi 10, cot x gtri hang trieu)

In [8]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
#ONE HOT ENCODING

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3) #30% test, 70 % train
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

#scale du lieu X
print(X_train_std[:5],X_train[:5])
print(y[:5])
#xuat lai du lieu ss vs ban dau



model = Perceptron(max_iter=40, eta0= 0.1, random_state=0)
# max_iter :so lan hoc
# eta0 : Toc do hoc [tu 0 den 1].
# random_state=0 trang thai  gtri ngau nhien
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('DO CHINH XAC MO HINH:',accuracy_score(y_test,y_pred))
# moi lan train se co gtri khac nhau 
# chon lan train co do chinh xac cao nhat

[[-0.01209799 -0.82944625  0.22925739 -0.22790376]
 [-0.7742716   0.72180818 -1.30363106 -1.25164257]
 [ 0.87710455 -0.16462292  1.19440938  1.30770446]
 [-1.15535841 -0.16462292 -1.30363106 -1.25164257]
 [ 1.13116242  0.50020041  1.13763573  1.17973711]] [[5.8 2.7 4.1 1. ]
 [5.2 3.4 1.4 0.2]
 [6.5 3.  5.8 2.2]
 [4.9 3.  1.4 0.2]
 [6.7 3.3 5.7 2.1]]
[0 0 0 0 0]
[2 1 0 0 1 0 1 1 0 1 2 1 2 2 2 2 2 0 2 2 2 0 0 2 2 2 2 2 0 0 2 2 2 2 2 2 1
 0 0 1 1 1 1 0 2]
[2 1 0 0 1 0 1 1 0 1 2 1 2 1 2 2 1 0 1 1 2 0 0 2 2 2 1 1 0 0 1 2 1 2 2 2 0
 0 0 1 1 1 1 0 2]
DO CHINH XAC MO HINH: 0.8


In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3) #30% test, 70 % train
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

#scale du lieu X
print(X_train_std[:5],X_train[:5])
print(y[:5])
#xuat lai du lieu ss vs ban dau
model = Perceptron(max_iter=1000, eta0= 0.5, random_state=0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('DO CHINH XAC MO HINH:',accuracy_score(y_test,y_pred))

[[ 2.19620261  0.01432989  1.24955583  1.39329696]
 [ 0.62171912  0.51587615  0.78858662  1.39329696]
 [-1.92167728  0.01432989 -1.63150175 -1.55947   ]
 [-0.95276437 -1.23953575 -0.53669987 -0.2173032 ]
 [-0.34719379 -1.23953575 -0.0181095  -0.2173032 ]] [[7.7 3.  6.1 2.3]
 [6.4 3.2 5.3 2.3]
 [4.3 3.  1.1 0.1]
 [5.1 2.5 3.  1.1]
 [5.6 2.5 3.9 1.1]]
[0 0 0 0 0]
[0 1 0 1 1 2 2 2 0 1 2 1 2 0 0 1 2 1 0 2 2 1 2 2 0 2 2 0 1 0 0 0 1 1 1 0 0
 0 0 0 0 1 0 0 0]
[0 2 0 1 1 2 2 2 0 1 2 1 2 0 0 1 2 1 0 2 2 1 2 2 0 2 2 0 1 0 0 0 1 1 1 0 0
 0 0 0 0 1 0 0 0]
DO CHINH XAC MO HINH: 0.9777777777777777


In [13]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt


url = 'crabs.csv'
crabs = pd.read_csv(url)

data=crabs.replace(["F","M","B","O"],[0,1,0,1])
data.head(150)
X = data.sex
y = data.speies
print(y[:20])
print(X[:20])

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: speies, dtype: int64
0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
Name: sex, dtype: int64


In [16]:
url = 'crabs.csv'
dataFrame = pd.read_csv(url)
dataFrame_total = dataFrame.replace(['B','M','O','F'], [0,0,1,1])
print(dataFrame_total)

     speies  sex  index  fontallip  rearwidth  length  width  depth
0         0    0      1        8.1        6.7    16.1   19.0    7.0
1         0    0      2        8.8        7.7    18.1   20.8    7.4
2         0    0      3        9.2        7.8    19.0   22.4    7.7
3         0    0      4        9.6        7.9    20.1   23.1    8.2
4         0    0      5        9.8        8.0    20.3   23.0    8.2
..      ...  ...    ...        ...        ...     ...    ...    ...
195       1    1     46       21.4       18.0    41.2   46.2   18.7
196       1    1     47       21.7       17.1    41.7   47.2   19.6
197       1    1     48       21.9       17.2    42.6   47.4   19.5
198       1    1     49       22.5       17.2    43.0   48.7   19.8
199       1    1     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [14]:
from sklearn.linear_model import Perceptron
from sklearn import datasets 
from sklearn.model_selection import train_test_split


from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler


In [17]:

x = dataFrame_total.drop('speies', axis = 1)
y = dataFrame_total.speies
print(x[:5])
print("---------------------------------------------------------")
print(y[:5])

   sex  index  fontallip  rearwidth  length  width  depth
0    0      1        8.1        6.7    16.1   19.0    7.0
1    0      2        8.8        7.7    18.1   20.8    7.4
2    0      3        9.2        7.8    19.0   22.4    7.7
3    0      4        9.6        7.9    20.1   23.1    8.2
4    0      5        9.8        8.0    20.3   23.0    8.2
---------------------------------------------------------
0    0
1    0
2    0
3    0
4    0
Name: speies, dtype: int64


In [21]:

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
print(x_train_std[:5], x_train[:5])
print(y[:5])

[[-1.02899151 -0.05581184  0.38234441 -0.13988391  0.35389524  0.26188394
   0.42924823]
 [ 0.97182532 -1.59063746 -0.96333704 -0.57245664 -1.11150949 -1.16915517
  -0.84806937]
 [ 0.97182532 -1.10228385 -1.44180156 -1.24097814 -1.47786067 -1.48716386
  -1.85167605]
 [ 0.97182532 -1.52087266 -1.89036205 -1.87017484 -1.90282804 -1.92442581
  -1.97332535]
 [-1.02899151  0.36277696  0.6514807   0.17471444  0.60301405  0.57989263
   0.85502076]]      sex  index  fontallip  rearwidth  length  width  depth
125    0     26       17.1       12.6    35.0   38.9   15.7
153    1      4       12.6       11.5    25.0   28.1   11.5
60     1     11       11.0        9.8    22.5   25.7    8.2
54     1      5        9.5        8.2    19.6   22.4    7.8
131    0     32       18.0       13.4    36.7   41.3   17.1
0    0
1    0
2    0
3    0
4    0
Name: speies, dtype: int64


In [22]:

model = Perceptron(max_iter=300, eta0=0.6,random_state=0) #maxinter : so lan hoc, eta0 : toc do hoc, randomstate : gia tri ngau nhien cua he thong
model.fit(x_train_std,y_train)
y_pred = model.predict(x_test_std)
print(y_pred[:5])
print(y_test[:5])
print("Độ chính xác của mô hình: ", accuracy_score(y_test,y_pred))
     

[0 0 1 0 0]
51     0
23     0
179    1
3      0
61     0
Name: speies, dtype: int64
Độ chính xác của mô hình:  1.0
