In [ ]:
from sklearn.linear_model import Perceptron

x = [[0,0],[0,1],[1,0],[1,1]]
t = [0,1,1,1]

model = Perceptron()
model.fit(x,t)
model.score(x,t)
#   x1   x2   t
#    0   0    0
#    0   1    1
#    1   0    1
#    1   1    1


1.0

In [ ]:
x1 = [[0.5,0.5],[-0.5,-0.5],[10,2.3],[-1,-2]]
y1 = model.predict(x1)
model.score(x1,y1)


1.0

In [ ]:
x1 = [[0.5,0.5],[-0.5,-0.5],[10,2.3],[-1,-2]]
y1 = model.predict(x1)
model.score(x1,y1)
print(y1)

[1 0 1 0]


In [ ]:
x1 = [[0.5,0.5],[0.5,0],[0,0.5],[0.4,0]]
y1 = model.predict(x1)
model.score(x1,y1)
print(y1)

[1 0 0 0]


In [ ]:
from sklearn.linear_model import Perceptron

x = [[-0.5,-0.5],[-0.5,0.5],[0.5,-0.5],[-0.1,1]]
t = [1,1,0,0]
model = Perceptron()
model.fit(x,t)
model.score(x,t)


1.0

In [ ]:
x1 = [[2,2],[-2,-2],[0.5,-0.5],[-0.1,1]]
y1 = model.predict(x1)
model.score(x1,y1)
print(y1)

[1 0 0 1]


In [ ]:
from sklearn.linear_model import Perceptron
from sklearn import datasets 
from sklearn.model_selection import train_test_split
#du lieu da train ko dc dung de test

from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler  #scale du lieu  de xu  li (du lieu ko deu, vd cot y gia tri tu 1 toi 10, cot x gtri hang trieu)

In [ ]:
iris = datasets.load_iris()
X = iris.data
y = iris.target
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [ ]:
#ONE HOT ENCODING

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3) #30% test, 70 % train
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

#scale du lieu X
print(X_train_std[:5],X_train[:5])
print(y[:5])
#xuat lai du lieu ss vs ban dau



model = Perceptron(max_iter=40, eta0= 0.1, random_state=0)
# max_iter :so lan hoc
# eta0 : Toc do hoc [tu 0 den 1].
# random_state=0 trang thai  gtri ngau nhien
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('DO CHINH XAC MO HINH:',accuracy_score(y_test,y_pred))
# moi lan train se co gtri khac nhau 
# chon lan train co do chinh xac cao nhat

[[-0.20318071 -0.09490562  0.1801862  -0.05283056]
 [ 2.05438271 -1.04396184  1.709611    1.40000997]
 [-0.88044973  0.61688654 -1.23594787 -0.97736545]
 [ 1.60287002 -0.33216968  1.36973883  0.73962791]
 [ 0.47408832  0.61688654  1.19980274  1.66416279]] [[5.7 3.  4.2 1.2]
 [7.7 2.6 6.9 2.3]
 [5.1 3.3 1.7 0.5]
 [7.3 2.9 6.3 1.8]
 [6.3 3.3 6.  2.5]]
[0 0 0 0 0]
[2 0 2 2 0 1 2 2 2 0 0 1 2 2 0 1 0 2 2 1 0 1 2 0 1 0 0 0 0 1 0 1 2 0 0 2 1
 2 0 0 2 0 0 0 0]
[2 0 2 2 0 1 2 2 2 0 0 1 2 2 0 1 0 2 2 1 1 1 2 0 1 0 0 0 0 1 0 1 2 0 0 2 1
 2 1 0 1 0 0 0 1]
DO CHINH XAC MO HINH: 0.9111111111111111


In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3) #30% test, 70 % train
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

#scale du lieu X
print(X_train_std[:5],X_train[:5])
print(y[:5])
#xuat lai du lieu ss vs ban dau
model = Perceptron(max_iter=1000, eta0= 0.5, random_state=0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('DO CHINH XAC MO HINH:',accuracy_score(y_test,y_pred))

[[ 1.66700665 -0.24077393  1.18074831  0.55997299]
 [-0.84718601 -1.49232158 -0.37175618 -0.07912662]
 [ 0.35004859 -1.24201205  1.06985513  0.30433314]
 [-0.96690947 -1.99294065 -0.20541641 -0.20694654]
 [-0.84718601  1.01077372 -1.25890159 -1.22950591]] [[7.2 3.  5.8 1.6]
 [5.1 2.5 3.  1.1]
 [6.1 2.6 5.6 1.4]
 [5.  2.3 3.3 1. ]
 [5.1 3.5 1.4 0.2]]
[0 0 0 0 0]
[2 1 0 1 1 2 1 2 1 0 1 1 1 0 1 0 1 1 1 2 0 0 1 1 0 0 1 1 0 1 2 1 0 1 1 1 1
 2 1 0 0 1 0 0 1]
[2 2 0 1 2 2 1 2 2 0 1 2 1 0 1 1 1 2 1 2 0 0 1 1 0 1 1 2 0 2 2 1 0 1 2 2 1
 2 1 1 0 1 0 0 1]
DO CHINH XAC MO HINH: 0.7333333333333333


In [ ]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt


url = 'crabs.csv'
crabs = pd.read_csv(url)

data=crabs.replace(["F","M","B","O"],[0,1,0,1])
data.head(150)
X = data.sex
y = data.speies
print(y[:20])
print(X[:20])

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
Name: speies, dtype: int64
0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
Name: sex, dtype: int64


In [ ]:
from sklearn.linear_model import Perceptron
from sklearn import datasets 
from sklearn.model_selection import train_test_split


from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [ ]:

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3) #30% test, 70 % train
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)


print(X_train_std[:5],X_train[:5])
print(y[:5])




model = Perceptron(max_iter=40, eta0= 0.1, random_state=0)
# max_iter :so lan hoc
# eta0 : Toc do hoc [tu 0 den 1].
# random_state=0 trang thai  gtri ngau nhien
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)
print(y_pred)
print(y_test)
print('DO CHINH XAC MO HINH:',accuracy_score(y_test,y_pred))
# moi lan train se co gtri khac nhau 
# chon lan train co do chinh xac cao nhat

ValueError: ignored